   const classesData = [
    {
      id: 1,
      course: "MERN Stack Development",
      topic: "React Hooks & useEffect",
      date: "2026-05-20",
      time: "18:00", // 6:00 PM
      duration: "2 Hours",
      students: 42,
      mode: "Online",
    },
    {
      id: 2,
      course: "React.js Advanced",
      topic: "Redux Toolkit",
      date: "2026-05-21",
      time: "09:00",
      duration: "1.5 Hours",
      students: 35,
      mode: "Online",
    },
    {
      id: 3,
      course: "Node.js & Express",
      topic: "REST API Authentication",
      date: "2026-05-20",
      time: "14:00",
      duration: "2 Hours",
      students: 28,
      mode: "Offline",
    },
    {
      id: 4,
      course: "Python Programming",
      topic: "Functions and Modules",
      date: "2026-05-23",
      time: "11:00",
      duration: "2 Hours",
      students: 55,
      mode: "Online",
    },
    {
      id: 5,
      course: "Machine Learning",
      topic: "Linear Regression",
      date: "2026-05-24",
      time: "16:30",
      duration: "2 Hours",
      students: 31,
      mode: "Online",
    },
  ];
export default classesData;
